Repository astriaorg/astria-release-test, pull requests merged in 2025-05, with the labels that each got.

#23 Enhance reusable Docker build workflow
  .github/workflows/reusable-docker-build.yml
Labels: ci, docker-build

#28 chore: test release-please conf
  .github/workflows/release-please.yml
  .release-please-config.json
  .release-please-manifest.json
Labels: ci

#35 chore: Refactor release workflows and remove release-test.yml
  .github/workflows/release-please.yml
  .github/workflows/release-test.yml
  .github/workflows/reusable-run-checker.yml
Labels: ci

#38 fix: test chart update
  charts/sequencer/values.yaml
Labels: cd

#41 fix(sequencer): more comments
  crates/astria-sequencer/build.rs
Labels: sequencer

#52 fix(sequencer): test-3
  Cargo.lock
  crates/astria-sequencer/src/app/storage/keys.rs
Labels: sequencer

#83 chore(workflow): enhance reusable-build.yml with platform specifications and version extraction step
  .github/workflows/reusable-build.yml
Labels: ci
